version: 2
jobs:
  build:
    working_directory: ~/snippets-js
    docker:
      - image: circleci/node:12.1.0
    steps:
      - checkout

      - run:
         name: update-npm
         command: 'sudo npm install -g npm@latest'

      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "packages.lock" }}
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile

      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ checksum "packages.lock" }}
          paths:
            - ~/.cache/npm

      - run:
          name: test
          command: npm test

      #- run:
      #    name: code-coverage
      #    command: './node_modules/.bin/nyc report --reporter=text-lcov'

      #- store_artifacts:
      #    # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #    path: test-results.xml
      #    prefix: tests

      #- store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
      #    path: coverage
      #    prefix: coverage

      #- store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      #    path: test-results.xml

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
