version: 2
jobs:
  build:
    working_directory: ~/snippets-js
    docker:
      - image: circleci/node:12.1.0
    steps:
      - checkout

      - run:
         name: update-npm
         command: 'sudo npm install -g npm@latest'

      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "packages.lock" }}
      - run:
          name: Install Dependencies
          command: npm install --frozen-lockfile

      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ checksum "packages.lock" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Run tests with coverage
          command: npx jest --coverage

      - store_artifacts:
         path: test-results.xml
         prefix: tests

      - store_artifacts:
         path: coverage
         prefix: coverage

      - store_test_results:
         path: test-results.xml

      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
